vae:
  resume: False
  amp: True
  base_learning_rate: 1.0e-4
  max_iter: 200000
  log_freq: 5000
  eval_freq: 1000
  eval_samples: 4
  params:
    embed_dim: 4
    perceptual_weight: 4.0
    lossconfig:
      params:
        disc_start: 10000 # Start training the GAN from disc_start * 3 steps
  vaeconfig:
    channels: 192
    resolution: 128 # For non-square images set a tuple [h, w] (e.g. resolution: [128, 256])
    cond_frames: 2
    pred_frames: 8
    in_channels: 3
    out_channels: 3
    splits: 1

model:
  base_learning_rate: 1.0e-4
  cond_prob: 0.7
  eval_freq: 1000
  eval_samples : 4
  log_freq: 5000
  resume: False
  max_iter: 250000
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    log_every_t: 200
    timesteps: 500
    w: 0
  sit_config:
    input_size: 32
    in_channels: 4
    encoder_depth: 4
    bn_momentum: 0.1